# Generated by Django 4.2.30 on 2026-05-06 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('employer', 'Employer')], default='student', max_length=10),
        ),
    ]
