# Generated by Django 4.2.30 on 2026-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internship_employer_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
