# Generated by Django 4.2.30 on 2026-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_internship_is_approved_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
